= Contributor Guide
:toc-placement: preamble
:toc:
:toclevels: 3
// Uris
:uri-forking: https://guides.github.com/activities/forking/
:uri-pull-request: https://help.github.com/articles/creating-a-pull-request-from-a-fork/
:uri-edit-files: https://help.github.com/articles/editing-files-in-your-repository/
:uri-local-clone: https://help.github.com/articles/cloning-a-repository-from-github/
== Preamble

Hi! We're excited to have you as a contributor.

Take a moment to review this document in order to make the contribution process easy and effective for everyone involved.

Following these guidelines helps to communicate that you respect the time of the developers managing and developing this open source project. In return, they should reciprocate that respect in addressing your issue or assessing patches and features.

== Things to know

- You must use `git commit --signoff` for any commit to be merged, and agree that usage of `--signoff` constitutes agreement with the terms of link:./DCO_1_1.adoc[DCO 1.1].
- We ask all of our community members and contributors to adhere to the link:./CODE_OF_CONDUCT.adoc[Mantoso Code of Conduct]. If you have questions, or need assistance, please reach out to our community team at codeofconduct@mantoso.com.


== Getting Started

To contribute to this repository you will {uri-forking}[fork this repository], push changes to a branch in your fork, and then {uri-pull-request}[create as a pull request] from that branch to the `master` branch of this repository.Forking only needs to be done once, after which you can push changes to your fork using the GitHub website file editor or from a local clone, as described below.

=== Information for newcomers

The documentation below describes common cases for contributors. If you have any questions, please do not hesitate to ask in link:https://gitter.im/jenkinsci/newcomer-contributors[newcomers] or link:https://gitter.im/jenkinsci/docs[Documentation SIG] Gitter chats.If you have any feedback about your contributor experience, please also share it with us in these channels so that we can improve our guidelines.

You can also find some newbie-friendly issues in our task tracker:

* link:../../issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22[Good First Issues on GitHub]

=== Creating a fork

Creating a fork, aka {uri-forking}[forking], makes a personal copy of another repository. Any changes you make in your fork of the repository will not show up on the website until they are merged (via pull request) to the `master` branch of this repository. If you are unfamiliar with how to create a fork or how forks work, see the {uri-forking}[GitHub tutorial on forking].

=== Edit files on Github

GitHub makes it easy to add, edit, or delete individual files via their website's {uri-edit-files}[File Editor]. This has the advantage of using the file editor is that GitHub will automatically fork (if needed), push the changes to a branch, and open a pull request for you. It also means you don't need to have a local clone of your fork. The disadvantage is that you can't verify you changes locally before creating the PR, it only works on one file at a time, and your changes are lost if you close or navigate away from the page.

=== Using a local clone

We generally recommend making changes in a {uri-local-clone}[local clone] of your fork. This requires some additional tools and storage on your local machine, and you will need a bit more technical knowledge of how to use those tools. However, this will allow you work on multiple files as part of a single set of changes. You'll save your changes in a local branch and then test them locally. When they are ready you will push your changes to your your fork and submit a pull request from there.

== Reviewing changes

There are many pull requests being submitted every week. Reviews are driven by the community, and any contributions are always welcome.

Some tips:

- Pull requests are open to public, and any GitHub user can review changes and provide feedback. If you are interested to review changes, please just do so (and thanks in advance!). No special permissions needed
